#
# Makefile for the sw_touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SW_TOUCHSCREEN_GSLX680)    += gslX680.o
obj-$(CONFIG_SW_TOUCHSCREEN_GT82X)      += gt82x.o
obj-$(CONFIG_SW_TOUCHSCREEN_ZET622X)    += zet622x.o
obj-$(CONFIG_SW_TOUCHSCREEN_SUNXI_TS)   += sunxi-ts.o
obj-$(CONFIG_SW_TOUCHSCREEN_GT811)      += gt811.o

obj-$(CONFIG_SW_TOUCHSCREEN_GT9XX)      += gt9xx/
obj-$(CONFIG_SW_TOUCHSCREEN_FT5X)       += ft5x/

